org: hbgworks
service: timeslots-gateway-resource

frameworkVersion: ^3.26.0

custom: ${file(../../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1
  endpointType: regional

  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId

resources:
  Resources:
    ApiGatewayResourceTimeSlots:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: ${self:provider.apiGateway.restApiId}
        ParentId: ${self:provider.apiGateway.restApiRootResourceId}
        PathPart: timeslots

  Outputs:
    ApiGatewayResourceTimeSlots:
      Value: !Ref ApiGatewayResourceTimeSlots
      Export:
        Name: ${self:custom.stage}-ExtApiGatewayResourceTimeSlots
