service: queues-viva

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:

    EventBridgeDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.resourcesStage}-EventBridgeDeadLetterQueue
        MessageRetentionPeriod: 345600  # 4 days
        KmsMasterKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master

    EventBridgeToDeadLetterQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: SQS:SendMessage
              Resource: !Sub arn:aws:sqs:${self:provider.region}:${AWS::AccountId}:${self:custom.stage}-EventBridgeDeadLetterQueue
        Queues:
          - !Ref EventBridgeDeadLetterQueue

    VivaSubmissionDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.resourcesStage}-VivaSubmissionDeadLetterQueue
        MessageRetentionPeriod: 1209600  # 14 days
        RedriveAllowPolicy: 
          redrivePermission: byQueue
          sourceQueueArns:
            - !Sub arn:aws:sqs:${self:provider.region}:${AWS::AccountId}:${self:custom.stage}-VivaSubmissionQueue
        KmsMasterKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master

    VivaSubmissionToVivaDeadLetterQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: sqs.amazonaws.com
              Action: SQS:SendMessage
              Resource: !Sub arn:aws:sqs:${self:provider.region}:${AWS::AccountId}:${self:custom.stage}-VivaSubmissionQueue
        Queues:
          - !Ref VivaSubmissionDeadLetterQueue

    VivaSubmissionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.resourcesStage}-VivaSubmissionQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt VivaSubmissionDeadLetterQueue.Arn
          maxReceiveCount: 10
        VisibilityTimeout: 120
        KmsMasterKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master

    EventBridgeToVivaQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: SQS:SendMessage
              Resource: !GetAtt VivaSubmissionQueue.Arn
        Queues:
          - Ref: VivaSubmissionQueue

    PostToVivaQueue:
      Type: "AWS::Events::Rule"
      Properties:
        Targets:
          - Arn: !GetAtt VivaSubmissionQueue.Arn
            Id: "VivaSubmissionQueue"
        EventPattern:
          source:
            - cases.database
          detail-type:
            - MODIFY
          detail:
            dynamodb:
              NewImage:
                provider:
                  S: ["VIVA"]
                status:
                  M:
                    type:
                      S: [{ "prefix": "active:submitted" }]
                state:
                  S: ["PDF_GENERATED"]

    DeadLetterQueueAlarmTopic:
      Type: AWS::SNS::Topic

    QueueDepthAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: "Alarm if queue depth grows beyond 1 messages"
        Namespace: "AWS/SQS"
        MetricName: ApproximateNumberOfMessagesVisible
        Dimensions:
          - Name: QueueName
            Value: !GetAtt VivaSubmissionDeadLetterQueue.QueueName
        Statistic: Sum
        Period: 300
        EvaluationPeriods: 1
        Threshold: 0
        ComparisonOperator: GreaterThanThreshold
        AlarmActions:
          - Ref: DeadLetterQueueAlarmTopic

  Outputs:
    VivaSubmissionQueueArn:
      Value: !GetAtt VivaSubmissionQueue.Arn
      Export:
        Name: ${self:custom.stage}-VivaSubmissionQueueArn

    EventBridgeDeadLetterQueueArn:
      Value: !GetAtt EventBridgeDeadLetterQueue.Arn
      Export:
        Name: ${self:custom.stage}-EventBridgeDeadLetterQueueArn
