service: queues-viva

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    VivaSubmissionQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.resourcesStage}-VivaSubmissionQueue

    EventBridgeToVivaQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: SQS:SendMessage
              Resource: !GetAtt VivaSubmissionQueue.Arn
        Queues:
          - Ref: VivaSubmissionQueue

    PostToVivaQueue:
      Type: "AWS::Events::Rule"
      Properties:
        Targets:
          - Arn: !GetAtt VivaSubmissionQueue.Arn
            Id: "VivaSubmissionQueue"
        EventPattern:
          source:
            - cases.database
          detail-type:
            - MODIFY
          detail:
            dynamodb:
              NewImage:
                provider:
                  S: ["VIVA"]
                status:
                  M:
                    type:
                      S: [{ "prefix": "active:submitted" }]
                state:
                  S: ["PDF_GENERATED"]

  Outputs:
    VivaSubmissionQueueArn:
      Value:
        Fn::GetAtt:
          - VivaSubmissionQueue
          - Arn
      Export:
        Name: ${self:custom.stage}-VivaSubmissionQueue
