service: database-user

custom:
  stage: ${file(../../serverless.common.yml):custom.stage}
  tableName: ${self:custom.stage}-users

provider:
  name: aws
  stage: dev
  region: eu-north-1

  environment:
    stage: ${self:custom.stage}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    UsersTableArn:
      Value:
        Fn::GetAtt:
          - UsersTable
          - Arn
      Export:
        Name: ${self:custom.stage}-UsersTableArn
