org: hbgworks
service: cases-dynamodb

frameworkVersion: ^3.26.0

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

  deploymentBucket:
    name: ${self:custom.deploymentBucket}

resources:
  Resources:
    CasesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-cases
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1
            AttributeType: S
          - AttributeName: GSI2PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expirationTime
          Enabled: true
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        SSESpecification:
          KMSMasterKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master
          SSEEnabled: true
          SSEType: KMS
        GlobalSecondaryIndexes:
          - IndexName: GSI1-SK-index
            KeySchema:
              - AttributeName: GSI1
                KeyType: HASH
              - AttributeName: SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: GSI2PK-index
            KeySchema:
              - AttributeName: GSI2PK
                KeyType: HASH
            Projection:
              ProjectionType: ALL

  Outputs:
    CasesTableArn:
      Value:
        Fn::GetAtt:
          - CasesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-CasesTableArn

    CasesTableAllIndexArn:
      Value:
        Fn::Join: ['/', ['Fn::GetAtt': [CasesTable, Arn], 'index', '*']]
      Export:
        Name: ${self:custom.stage}-CasesTableAllIndexArn

    CasesTableStreamArn:
      Value:
        Fn::GetAtt:
          - CasesTable
          - StreamArn
      Export:
        Name: ${self:custom.stage}-CasesTableStreamArn
