service: cases-dynamodb

custom:
  stage: ${file(../../../serverless.common.yml):custom.stage}
  tableName: ${self:custom.stage}-cases

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    CasesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: formId
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        SSESpecification:
          KMSMasterKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master
          SSEEnabled: true
          SSEType: KMS
        GlobalSecondaryIndexes:
          - IndexName: PK-formId-gsi
            KeySchema: 
              - AttributeName: PK
                KeyType: HASH
              - AttributeName: formId
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - answers
                - details
                - SK
                - updatedAt
                - createdAt
                - id 
                - provider
                - status
              ProjectionType: INCLUDE

  Outputs:
    CasesTableArn:
      Value:
        Fn::GetAtt:
          - CasesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-CasesTableArn

    CasesTableStreamArn:
      Value:
        Fn::GetAtt:
          - CasesTable
          - StreamArn
      Export:
        Name: ${self:custom.stage}-CasesTableStreamArn
