service: database-user

custom:
  stage: ${file(../../serverless.common.yml):custom.stage}
  tableName: ${self:custom.stage}-user

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    UserTableArn:
      Value:
        Fn::GetAtt:
          - UserTable
          - Arn
      Export:
        Name: ${self:custom.stage}-UserTableArn
