org: hbgworks
service: users-dynamodb

frameworkVersion: ^3.26.0

plugins:
  - serverless-deployment-bucket

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

  deploymentBucket:
    name: ${self:custom.deploymentBucketName}

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-users
        AttributeDefinitions:
          - AttributeName: personalNumber
            AttributeType: S
        KeySchema:
          - AttributeName: personalNumber
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          KMSMasterKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master
          SSEEnabled: true
          SSEType: KMS

  Outputs:
    UsersTableArn:
      Value:
        Fn::GetAtt:
          - UsersTable
          - Arn
      Export:
        Name: ${self:custom.stage}-UsersTableArn
