service: hbg-dynamodb-forms

custom:
  stage: ${file(../../../serverless.common.yml):custom.stage}
  tableName: ${self:custom.stage}-forms

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    FormsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

  Outputs:
    FormsTableArn:
      Value:
        Fn::GetAtt:
          - FormsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-FormsTableArn
