service: forms-dynamodb

custom:
  stage: ${file(../../../serverless.common.yml):custom.stage}
  tableName: ${self:custom.stage}-forms

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    FormsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          KMSMasterKeyId: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master
          SSEEnabled: true
          SSEType: KMS

  Outputs:
    FormsTableArn:
      Value:
        Fn::GetAtt:
          - FormsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-FormsTableArn
