org: hbgworks
service: forms-dynamodb

frameworkVersion: ^3.26.0

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

  deploymentBucket:
    name: ${self:custom.deploymentBucket}

resources:
  Resources:
    FormsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.stage}-forms
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  Outputs:
    FormsTableArn:
      Value:
        Fn::GetAtt:
          - FormsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-FormsTableArn
