org: hbgworks
service: booking-gateway-resource

frameworkVersion: ^3.26.0

custom: ${file(../../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

  deploymentBucket:
    name: ${self:custom.deploymentBucket}

  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId

resources:
  Resources:
    ApiGatewayResourceBooking:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: ${self:provider.apiGateway.restApiId}
        ParentId: ${self:provider.apiGateway.restApiRootResourceId}
        PathPart: booking

  Outputs:
    ApiGatewayResourceBooking:
      Value: !Ref ApiGatewayResourceBooking
      Export:
        Name: ${self:custom.stage}-ExtApiGatewayResourceBooking
