service: helsingborg-io-sls-certificates

custom: ${file(../../serverless.common.yml):custom}

provider: ${file(../../serverless.common.yml):provider}

resources:
  Resources:
    CertificatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              MaxAge: 3000

  # Print out the name of the bucket that is created
  Outputs:
    CertificatesBucketArn:
      Value:
        Fn::GetAtt:
          - CertificatesBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-CertificatesBucketArn
