service: helsingborg-io-sls-certificates

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    CertificatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              MaxAge: 3000

  # Print out the name of the bucket that is created
  Outputs:
    CertificatesBucketArn:
      Value:
        Fn::GetAtt:
          - CertificatesBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-CertificatesBucketArn
