service: helsingborg-io-sls-certificates

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the bucket name here so we can use it while testing locally
  bucketName: ${self:custom.stage}-certificates

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    certificatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

  # Print out the name of the bucket that is created
  Outputs:
    CertificatesBucketArn:
      Value:
        Fn::GetAtt:
          - certificatesBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-CertificatesBucketArn

    CertificatesBucketName:
      Value:
        Ref: certificatesBucket
      Export:
        Name: ${self:custom.stage}-CertificatesBucket
