service: helsingborg-io-sls-database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-submissions

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    SubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: submissionId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: submissionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

  Outputs:
    SubmissionsTableArn:
      Value:
        Fn::GetAtt:
          - SubmissionsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-SubmissionsTableArn
