service: helsingborg-io-sls-database

custom:
  stage: ${file(../../serverless.common.yml):custom.stage}
  tableName: ${self:custom.stage}-submissions

provider: ${file(../../serverless.common.yml):provider}

resources:
  Resources:
    SubmissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: submissionId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: submissionId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

  Outputs:
    SubmissionsTableArn:
      Value:
        Fn::GetAtt:
          - SubmissionsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-SubmissionsTableArn
