service: pdf-storage

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    PdfStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

  Outputs:
    PdfStorageBucketArn:
      Value:
        Fn::GetAtt:
          - PdfStorageBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-PdfStorageBucketArn

    PdfStorageBucketName:
      Value: !Ref PdfStorageBucket

      Export:
        Name: ${self:custom.stage}-PdfStorageBucketName
