org: hbgworks
service: pdf-storage

frameworkVersion: ^3.26.0

plugins:
  - serverless-deployment-bucket

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

  deploymentBucket:
    name: ${self:custom.deploymentBucketName}

resources:
  Resources:
    PdfStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'aws:kms'
                KMSMasterKeyID: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master
              BucketKeyEnabled: true

        LifecycleConfiguration:
          Rules:
            - Id: 'expire-pdf-rule'
              Status: Enabled
              Prefix: 'pdf/'
              ExpirationInDays: 3
            - Id: 'expire-html-rule'
              Status: Enabled
              Prefix: 'html/'
              ExpirationInDays: 3
  Outputs:
    PdfStorageBucketArn:
      Value:
        Fn::GetAtt:
          - PdfStorageBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-PdfStorageBucketArn

    PdfStorageBucketName:
      Value: !Ref PdfStorageBucket

      Export:
        Name: ${self:custom.stage}-PdfStorageBucketName
