service: pdf-storage

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    PdfStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

  Outputs:
    PdfStorageBucketArn:
      Value:
        Fn::GetAtt:
          - PdfStorageBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-PdfStorageBucketArn

    PdfStorageBucketName:
      Value: !Ref PdfStorageBucketArn

      Export:
        Name: ${self:custom.stage}-PdfStorageBucketName
