service: deployments-s3
projectDir: ../../../

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    DeploymentsBucketArn:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.deploymentBucket}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
