service: hbg-io-sls-api-resource-auth

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-north-1
  tracing:
    apiGateway: true

  apiGateway:
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

resources:
  Resources:
    ApiGatewayResourceAuth:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: ${self:provider.apiGateway.restApiId}
        ParentId: ${self:provider.apiGateway.restApiRootResourceId}
        PathPart: auth

  Outputs:
    ApiGatewayResourceAuth:
      Value:
        Ref: ApiGatewayResourceAuth
      Export:
        Name: ${self:custom.stage}-ExtApiGatewayResourceAuth
