service: certificates-s3
projectDir: ../../../

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    CertificatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

        # Set the CORS policy
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              MaxAge: 3000

        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'aws:kms'
                KMSMasterKeyID: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master
              BucketKeyEnabled: true

  # Print out the name of the bucket that is created
  Outputs:
    CertificatesBucketArn:
      Value:
        Fn::GetAtt:
          - CertificatesBucket
          - Arn
      Export:
        Name: ${self:custom.stage}-CertificatesBucketArn
