org: hbgworks
service: search-gateway-resource

frameworkVersion: ^3.26.0

plugins:
  - serverless-deployment-bucket

custom: ${file(../../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1
  endpointType: regional

  deploymentBucket:
    name: ${self:custom.deploymentBucketName}

  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId

resources:
  Resources:
    ApiGatewayResourceSearch:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: ${self:provider.apiGateway.restApiId}
        ParentId: ${self:provider.apiGateway.restApiRootResourceId}
        PathPart: search

  Outputs:
    ApiGatewayResourceSearch:
      Value: !Ref ApiGatewayResourceSearch
      Export:
        Name: ${self:custom.stage}-ExtApiGatewayResourceSearch
