org: hbgworks
service: attachments-s3

frameworkVersion: ^3.26.0

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    AttachmentsBucketArn:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Join
          - '-'
          - - 'attachments-s3'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref 'AWS::StackId'
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'aws:kms'
                KMSMasterKeyID: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/external/master
              BucketKeyEnabled: true
        AccessControl: Private
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
        LifecycleConfiguration:
          Rules:
            - Id: 'expire-all-rule'
              Status: Enabled
              ExpirationInDays: 3
        NotificationConfiguration:
          EventBridgeConfiguration:
            EventBridgeEnabled: true

  Outputs:
    AttachmentsBucketArn:
      Value:
        Fn::GetAtt:
          - AttachmentsBucketArn
          - Arn
      Export:
        Name: ${self:custom.stage}-AttachmentsBucketArn

    AttachmentsBucketName:
      Value: !Ref AttachmentsBucketArn
      Export:
        Name: ${self:custom.stage}-AttachmentsBucketName
