org: hbgworks
service: chrome-aws-lambda-layer

frameworkVersion: ^3.26.0

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  stage: dev
  region: eu-north-1

layers:
  chromeAws:
    path: executables
    name: chrome-aws-lambda-${self:custom.stage}
    description: Stores all the fonts and executable binaries required to convert html to pdf
    compatibleRuntimes:
      - nodejs12.x

resources:
  Outputs:
    ChromeAwsLambdaLayerArn:
      Value:
        Ref: ChromeAwsLambdaLayer
      Export:
        Name: ChromeAwsLambdaLayer-${self:custom.stage}
