service: chrome-aws-lambda-layer

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: eu-north-1
  endpointType: regional
  tracing:
    lambda: true

layers:
  chromeAws:
    path: executables
    name: chrome-aws-lambda-${self:provider.stage}
    description: Stores all the fonts and executable binaries required to convert html to pdf
    compatibleRuntimes: nodejs12.x

resources:
  Outputs:
    ChromeAwsLambdaLayerArn:
      Value:
        Ref: ChromeAwsLambdaLayer
      Export:
        Name: ChromeAwsLambdaLayer-${self:provider.stage}
